### ISSUE TITLE
Mismatch: Queries Sent and Response Count

### ISSUE THREAD

**Issue by abhay8nitt** [joomcode/redispipe#14]
Hi There,

We are using Redis pipe v0.9.4 to query AWS ES Cache - engine version 5.0.5. We are tracking the number of queries that we sent to the Redis and the number of responses we receive using a custom metric. We have modified timeouts a couple of times. We sometimes wait additionally for 500µs (microsecond) per request( If at certain time T we find that the responses didn't arrive for 30 out of 300 requests, we sleep for 500µs 30 times).

We would like to understand what all we should look at to get 100% responses in time, without taking a hit on our processing capacity ( eps). The cache hits can go up-to order of millions. We are using read replicas in our setup with reader endpoints.

Any tuning recommendations would be really appreciable.

Thanks,
Abhay

**Comment by abhay8nitt** [comment]
@funny-falcon-at-joomcode any help here? ( apologies for being impatient )

**Comment by abhay8nitt** [comment]
second try...

**Comment by akostrikov** [comment]
@funny-falcon :)

**Comment by funny-falcon** [comment]
It quite hard to respond without seeing example code and steps to reproduce.
For example, if you issue blocking redis commands, then it is certainly misuse of this library.

And I don't understand from your explanation: do requests disappear or time outs?

In our setup I've increased timeout up to 4 seconds. Yep, it is quite large, but it consequent with some internal tcp timeouts: sometimes requests between AWS availability zones are timed out because of lost packets and tcp retransmits (i believe so). And tcp retransmit could happen seconds after packet lost. I've never seen timeouts from client to redis server in same availability zone though (with 1-2 second timeout).
